### PR TITLE
applications supply packet buffers (rather than through the alloc_packet callback)

### PR DESCRIPTION
**Pull request by kazuho**
Up until now, we have had `quicly_packet_allocator` that is used for allocating memory for storing a packet image, associated with the source and destination addresses. While conceptually clean, this design has had issues:
* Unnecessary use of alloc - free. Typically, applications call `quicy_send` then immediately submits the UDP packets being built to the kernel. In such case, freedom for releasing things in arbitrary order (what heap allocation provides) is unnecessary and just costly.
* Unfriendliness with GSO. The prerequisite of GSO is that all packets contain the same 4-tuple. As the 4-tuple tuple contained in each packet generated by quicly can be different, __applications are required to consult the 4-tuple of each packet and route them to the correct socket (or underlying network interface)__. Also, it was hard to build all the UDP packet images in a contiguous range of memory. That resulted in the kernel doing gather operation when using GSO.

This PR changes the approach.

It eliminates the alloc_packet callback, and instead requires application to supply the buffer in which UDP packet images should be built, when calling functions like `quicly_send`.

In master, `quicly_send` function looks like:
```c
/**
 * Builds UDP datagrams to be sent for given connection.
 * @param [out] packets         vector of `quicly_datagram_t *`, each of the elements containing the 4-tuple and the datagram
 *                              payload. Each `quicly_datagram_t *` is allocated and freed using the alloc_packet callback provided
 *                              through `quicly_context_t`.
 * @param [in,out] num_packets  Upon entry, the application provides the number of entries that the `packets` vector can contain.
 *                              Upon return, contains the number of packet vectors emitted by `quicly_send`.
 * @return 0 if successful, otherwise an error. When an error is returned, the caller must call `quicly_close` to discard the
 *         connection context.
 */
int quicly_send(quicly_conn_t *conn, quicly_datagram_t **packets, size_t *num_packets);
```

With the proposed change, it becomes like:
```c
/**
 * Builds UDP datagrams to be sent for given connection.
 * @param [out] dest            destination address
 * @param [out] src             source address
 * @param [out] packets         vector of iovecs pointing to the payloads of UDP datagrams. Each iovec represens a single UDP
 *                              datagram.
 * @param [in,out] num_packets  Upon entry, the application provides the number of entries that the `packets` vector can contain.
 *                              Upon return, contains the number of packet vectors emitted by `quicly_send`.
 * @param buf                   buffer used for building UDP datagrams. It is guaranteed that the first datagram would be built from
 *                              the address provided by `buf`, and that succeeding packets (if any) will be contiguously laid out.
 *                              This constraint reduces the number of vectors that need to be passed to the kernel when using GSO.
 * @return 0 if successful, otherwise an error. When an error is returned, the caller must call `quicly_close` to discard the
 *         connection context.
 */
int quicly_send(quicly_conn_t *conn, quicly_address_t *dest, quicly_address_t *src, struct iovec *packets, size_t *num_packets,
                void *buf, size_t bufsize);
```

Other functions that emit packets (e.g., `quicly_send_version_negotiation`, `quicly_send_retry`) are also modified so that they would receive a buffer to which the UDP payloads are written.

### CODE REVIEW

**Comment by kazuho** [comment]
FWIW, with this PR, I see 7% reduction in "CPU time spent per Mbps" metric.

**Comment by kazuho** [comment]
@AloysAugustin I think we want to merge this PR, but wanted to ping you as it is my understanding that you use a custom `alloc_packet` callback.

As stated at the top, I think our current approach is suboptimal and inadequate as it requires per-packet routing. You might not have noticed this, because at the moment, quicly does not talk to multiple addresses for each connection. But we'd soon start doing that, as we add support for migration.

With this PR, we'd have a contractual guarantee that series of packets returned by a single call to `quicly_send` can be routed as one big block contained in a contiguous buffer. I think that this is a good simplification and will provide us better performance, reduce maintenance cost.

That said, I understand that there might be something missing in the current form of this PR. For example, this PR builds a series of UDP packet bodies (i.e., excluding IP and UDP header) in a contiguous chunk of memory supplied by the user. Some might want a callback for building packets with appropriate headers. I am eager to discuss what is missing and adding them as necessary.

Thank you in advance.

**Comment by sknat** [comment]
Hi @kazuho 

Jumping in on this discussion, I would +1 for merging this PR. Even if some things are missing I think it will improve the current behavior. In our use-case that'll help removing one layer of memcpy for most packets.

Few thought for potential future improvements :
It might be worth re-introducing some kind of packet allocator that would be called when exhausting the current buffer. This would allow to build chained buffers without having to make a full `quicly_send` call.
On that specific use-case another open question we have is the handling of 'border packets'. If we want to finish filling the first buffer before switching to the next one, is there a way to write a datagram to two distinct buffers ?

Concerning callbacks for writing UDP packet headers, I don't have a clear opinion. I think the GSO approach is to write them as late as possible, but there might be use-cases I'm not seeing here.

Thanks for your help
Cheers

**Comment by kazuho** [comment]
@sknat Thank you for sharing your thoughts. It's good to know that you could remove memcpy once this PR gets adopted.

> Few thought for potential future improvements :
> It might be worth re-introducing some kind of packet allocator that would be called when exhausting the current buffer. This would allow to build chained buffers without having to make a full `quicly_send` call.

We could do that, though I would like to understand why it would be beneficial.

Having such an optimization would make sense if it is going to be used often. But if it is going to be used often, why not supply a larger buffer instead?

In our case, each of our event loop would be doing quicly_send -> sendmsg using at most 64KB buffer. 64KB per CPU core is a tiny number compared to the sum of the sizes of the send windows of connections governed by that event loop.

I would also point out that applications should be reading ingress packets frequently rather than trying to build long list of packets, as building long list of packets without reading worsens the latency, therefore having negative impact on performance once loss occurs. My assumption has been that supplying at most ~64KB buffer to `quicly_send` would work well even on 10gbe networks, and if the size of the buffer is as large as that, I'd assume that making one more call to `quicly_send` would not be a cost. Though numbers might prove me wrong.

> Concerning callbacks for writing UDP packet headers, I don't have a clear opinion. I think the GSO approach is to write them as late as possible, but there might be use-cases I'm not seeing here.

Right, I think the question here is more about kernel-bypass. My thinking was that when doing kernel-bypass, it might be the case that you want to build IP /UDP headers yourself, enforce alignment on each packet being sent, etc.

**Comment by AloysAugustin** [comment]
Hi Kazuho,

Thanks for reaching out to us, I would also +1 this PR.

My only question would be about the size of the generated datagrams, can we assume that all (or all but the last) datagram have the same length?

**Comment by kazuho** [comment]
@AloysAugustin Thank you for checking. Glad to know that you'd be happy to see this happen.

> My only question would be about the size of the generated datagrams, can we assume that all (or all but the last) datagram have the same length?

That's a good point. At the moment we have not had that contract. Having that would simplify things; I've created #333 that accomplishes that.

**Pull request merged**
