### PR TITLE
QLog draft-02 support

### PR DESCRIPTION
**Pull request by toru**
Our current QLog output format is a mix of `draft-01` and `draft-02-wip`. In other words, invalid. Now that `draft-02` is finalized, this PR updates the `qlog-adapter` script to render payloads that comply with `draft-02`. To be specific, the [NDJSON format mapping](https://quiclog.github.io/internet-drafts/draft02/draft-marx-qlog-main-schema.html#name-qlog-to-ndjson-mapping) is implemented. Here's a cropped rendering from QVis:

Screen Shot 2021-01-29 at 2 48 57 PM

### CODE REVIEW

**Comment by toru** [comment]
@kazuho Are you ok with me merging this?

**Comment by kazuho** [comment]
@toru Thank you for working on this. I think I would delegate reviews regarding the conversion script to @janaiyengar.

**Comment by toru** [comment]
@kazuho That sounds good to me. Looking forward to hearing from @janaiyengar. Here's a live link to the data generated by the updated adapter.

- qvis: https://qvis.edm.uhasselt.be/#/files?file=https%3A%2F%2Ftorumk.com%2Fh2o%2Fdraft02.h2olog.qlog
- raw qlog: https://torumk.com/h2o/draft02.h2olog.qlog

**Review by janaiyengar — APPROVED** [review]
Thank you for working on this @toru!

**Pull request merged**
